ProjectManagement/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ProjectManagement.Models
{
    public enum Priority
    {
        Низкий = 1,
        Средний = 2,
        Высокий = 3,
        Критический = 4
    }

    public class Project
    {
        public Project()
        {
            this.ContractorEmployees = new HashSet<Employee>();
        }
        public int Id { get; set; }
        [DisplayName("Название")]
        public string Name { get; set; }
        [DisplayName("Компания заказчик")]
        public string CustomerCompanyName { get; set; }
        [DisplayName("Компания исполнитель")]
        public string ContractorCompanyName { get; set; }
        [DisplayName("Сотрудник")]
        public int EmployeeId { get; set; }
        [DisplayName("Руководитель проекта")]
        public int ProjectManagerId { get; set; }
        [DisplayName("Начало")]
        public DateTime StartDate { get; set; }
        [DisplayName("Конец")]
        public DateTime EndDate { get; set; }
        [DisplayName("Приоритет")]
        public int Priority { get; set; }
        [DisplayName("Коментарий")]
        public string Description { get; set; }

        [DisplayName("Сотрудник")]
        public virtual Employee Employee { get; set; }

        [DisplayName("Руководитель проекта")]
        public virtual Employee ProjectManager { get; set; }

        [DisplayName("Исполнители проекта")]
        public virtual ICollection<Employee> ContractorEmployees { get; set; }
    }

}

ProjectManagement/Controllers/ProjectsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectManagement.Models;
using ProjectManagement.DBContext;
using ProjectManagement.ViewModels;

namespace ProjectManagement.Controllers
{
    public class ProjectsController : Controller
    {
        private ProjectManagementContext db = new ProjectManagementContext();

        // GET: /Projects/
        public ActionResult Index()
        {
            var projects = db.Projects.Include(p => p.Employee).Include(p => p.ProjectManager);
            return View(projects);
        }

        // GET: /Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: /Projects/Create
        public ActionResult Create()
        {
            var project = new Project();
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Firstname");
            ViewBag.ProjectManagerId = new SelectList(db.Employees, "Id", "Firstname");
            PopulateAssignedContractorData(project);
            return View();
        }

        // POST: /Projects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,CustomerCompanyName,ContractorCompanyName,EmployeeId,ProjectManagerId,StartDate,EndDate,Priority,Description")] Project project, string[] selectedContractors)
        {
            if (selectedContractors != null)
            {
                project.ContractorEmployees = new List<Employee>();
                foreach (var contractor in selectedContractors)
                {
                    var employeeToAdd = db.Employees.Find(int.Parse(contractor));
                    project.ContractorEmployees.Add(employeeToAdd);
                }
            }
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Firstname", project.EmployeeId);
            ViewBag.ProjectManagerId = new SelectList(db.Employees, "Id", "Firstname", project.ProjectManagerId);
            PopulateAssignedContractorData(project);
            return View(project);
        }

        // GET: /Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects
                .Include(p => p.Employee)
                .Include(p => p.ProjectManager).Single(p => p.Id == id);
            PopulateAssignedContractorData(project);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Firstname", project.EmployeeId);
            ViewBag.ProjectManagerId = new SelectList(db.Employees, "Id", "Firstname", project.ProjectManagerId);
            return View(project);
        }

        // POST: /Projects/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string[] selectedContractors)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project projectToUpdate = db.Projects
                .Include(p => p.Employee)
                .Include(p => p.ProjectManager).Single(p => p.Id == id);
            if (TryUpdateModel(projectToUpdate, "",
                new string[]
                {
                    "Name", "CustomerCompanyName", "ContractorCompanyName", "EmployeeId", "ProjectManagerId", "StartDate",
                    "EndDate", "Priority", "Description"
                }))
            {
                try
                {
                    UpdateInstructorCourses(selectedContractors, projectToUpdate);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (RetryLimitExceededException /* dex */)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("",
                        "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            ViewBag.EmployeeId = new SelectList(db.Employees, "Id", "Firstname", projectToUpdate.EmployeeId);
            ViewBag.ProjectManagerId = new SelectList(db.Employees, "Id", "Firstname", projectToUpdate.ProjectManagerId);
            PopulateAssignedContractorData(projectToUpdate);
            return View(projectToUpdate);
        }

        private void UpdateInstructorCourses(string[] selectedContractors, Project projectToUpdate)
        {
            if (selectedContractors == null)
            {
                projectToUpdate.ContractorEmployees = new List<Employee>();
                return;
            }

            var selectedContractorsHs = new HashSet<string>(selectedContractors);
            var projectContractors = new HashSet<int>
                (projectToUpdate.ContractorEmployees.Select(ce => ce.Id));
            foreach (var employee in db.Employees)
            {
                if (selectedContractorsHs.Contains(employee.Id.ToString()))
                {
                    if (!projectContractors.Contains(employee.Id))
                    {
                        projectToUpdate.ContractorEmployees.Add(employee);
                    }
                }
                else
                {
                    if (projectContractors.Contains(employee.Id))
                    {
                        projectToUpdate.ContractorEmployees.Remove(employee);
                    }
                }
            }
        }

        // GET: /Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: /Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private void PopulateAssignedContractorData(Project project)
        {
            var allEmployees = db.Employees;
            var projectContractors = new HashSet<int>(project.ContractorEmployees.Select(ce => ce.Id));
            var viewModel = allEmployees.Select(employee => new AssignedContractorData
            {
                EmployeeId = employee.Id, Title = employee.Firstname, Assigned = projectContractors.Contains(employee.Id)
            }).ToList();
            ViewBag.Contractors = viewModel;
        }
    }
}

ProjectManagement/Views/Projects/Create.cshtml
@using System.Web.UI.HtmlControls
@using ProjectManagement.Models
@model ProjectManagement.Models.Project

@{
    ViewBag.Title = "Create";
}

<h2>Новый проект</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr/>
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new {@class = "control-label col-sm-2"})
            <div class="col-sm-10">
                @Html.TextBoxFor(model => model.Name, new {@class = "form-control input-sm"})
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="col-sm-12">
            <div class="row">

                <div class="form-group">
                    @Html.LabelFor(model => model.CustomerCompanyName, new {@class = "control-label col-sm-2"})
                    <div class="col-sm-4">
                        @Html.TextBoxFor(model => model.CustomerCompanyName, new {@class = "form-control input-sm"})
                        @Html.ValidationMessageFor(model => model.CustomerCompanyName)
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.ContractorCompanyName, new {@class = "control-label col-sm-2"})
                    <div class="col-sm-4">
                        @Html.TextBoxFor(model => model.ContractorCompanyName, new {@class = "form-control input-sm"})
                        @Html.ValidationMessageFor(model => model.ContractorCompanyName)
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="row">
                <div class="form-group">
                    @Html.LabelFor(model => model.EmployeeId, "Сотрудник", new {@class = "control-label col-sm-2"})
                    <div class="col-sm-4">
                        @Html.DropDownListFor(model => model.EmployeeId, (IEnumerable<SelectListItem>)ViewBag.EmployeeId,  "Выберите сотрудника ...", new { @class = "form-control input-sm" })
                        @Html.ValidationMessageFor(model => model.EmployeeId)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ProjectManagerId, "Руководитель", new {@class = "control-label col-sm-2"})
                    <div class="col-sm-4">
                        @Html.DropDownListFor(model => model.ProjectManagerId, (IEnumerable<SelectListItem>)ViewBag.ProjectManagerId, "Выберите руководителя ..." , new { @class = "form-control input-sm" })
                        @Html.ValidationMessageFor(model => model.ProjectManagerId)
                    </div>
                </div>

            </div>
        </div>
        <div class="col-sm-12">
            <div class="row">

                <div class="form-group">
                    @Html.LabelFor(model => model.StartDate, new {@class = "control-label col-sm-2"})
                    <div class="col-sm-4">
                        @Html.TextBoxFor(model => model.StartDate, new {@class = "form-control input-sm", @type = "date"})
                        @Html.ValidationMessageFor(model => model.StartDate)
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EndDate, new {@class = "control-label col-sm-2"})
                    <div class="col-sm-4">
                        @Html.TextBoxFor(model => model.EndDate, new {@class = "form-control input-sm", @type = "date"})
                        @Html.ValidationMessageFor(model => model.EndDate)
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="row">
                <div class="form-group">
                    @Html.LabelFor(model => model.Priority, new {@class = "control-label col-sm-2"})
                    <div class="col-sm-4">
                        @Html.DropDownList("Priority", EnumHelper.GetSelectList(typeof (Priority)), "Выберите приоритет ...", new {@class = "form-control input-sm"})
                        @Html.ValidationMessageFor(model => model.Priority)
                    </div>
                </div>

            </div>
        </div>
        <div class="col-sm-12">
            <div class="row">


                <div class="form-group">
                    @Html.LabelFor(model => model.Description, new {@class = "control-label col-sm-2"})
                    <div class="col-sm-4">
                        @Html.TextAreaFor(model => model.Description, new {@class = "form-control input-sm"})
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<ProjectManagement.ViewModels.AssignedContractorData> contractors = ViewBag.Contractors;

                            foreach (var contractor in contractors)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                    <input type="checkbox"
                                        name="selectedContractors"
                                        value="@contractor.EmployeeId"
                                        @(Html.Raw(contractor.Assigned ? "checked=\"checked\"" : "")) />
                                        @contractor.EmployeeId @:  @contractor.Title
                                @:</td>
                            }
                            @:</tr>
                        }
                </table>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-sm-6">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-2.2.0.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ProjectManagement/Views/Projects/Delete.cshtml
@model ProjectManagement.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employee.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectManager.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectManager.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerCompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerCompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContractorCompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContractorCompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjectManagement/Views/Projects/Details.cshtml
@model ProjectManagement.Models.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Project</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Employee.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Employee.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectManager.Firstname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectManager.Firstname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerCompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerCompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContractorCompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContractorCompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProjectManagement/Views/Projects/Edit.cshtml
@model ProjectManagement.Models.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerCompanyName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerCompanyName)
                @Html.ValidationMessageFor(model => model.CustomerCompanyName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContractorCompanyName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContractorCompanyName)
                @Html.ValidationMessageFor(model => model.ContractorCompanyName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, "EmployeeId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EmployeeId", String.Empty)
                @Html.ValidationMessageFor(model => model.EmployeeId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectManagerId, "ProjectManagerId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectManagerId", String.Empty)
                @Html.ValidationMessageFor(model => model.ProjectManagerId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate)
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority)
                @Html.ValidationMessageFor(model => model.Priority)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <table>
                    <tr>
                        @{
                            int cnt = 0;
                            List<ProjectManagement.ViewModels.AssignedContractorData> contractors = ViewBag.Contractors;

                            foreach (var contractor in contractors)
                            {
                                if (cnt++ % 3 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                     <input type="checkbox"
                                        name="selectedContractors"
                                        value="@contractor.EmployeeId"
                                        @(Html.Raw(contractor.Assigned ? "checked=\"checked\"" : "")) />
                                        @contractor.EmployeeId @:  @contractor.Title
                               @:</td>
                            }
                            @:</tr>
                        }
                    </table>
                </div>
            </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ProjectManagement/Views/Projects/Index.cshtml
@using ProjectManagement.Models
@model IEnumerable<ProjectManagement.Models.Project>

@{
    ViewBag.Title = "Index";
}

<div>

    <p class="pull-right">
        <a href='@Url.Action("Create", "Projects")'><span class="glyphicon glyphicon-plus"></span></a>
    </p>
    <h2>Список проектов</h2>

</div>

<div class="panel panel-default">
    @(Html
          .Grid(Model)
          .Build(columns =>
          {
              columns.Add(model => model.Name).Titled("Название");
              columns.Add(model => model.CustomerCompanyName).Titled("Заказчик");
              columns.Add(model => model.ContractorCompanyName).Titled("Исполнитель");
              columns.Add(model => model.Priority).Titled("Приоритет").RenderedAs(model=> (Priority)model.Priority);
              columns.Add(model => model.StartDate).Titled("Дата начала").Formatted("{0: dd.MM.yyyy}");
              columns.Add(model => model.EndDate).Titled("Дата конца").Formatted("{0: dd.MM.yyyy}");
              columns.Add(model => model.Id).Titled("")
                  .RenderedAs(model => String.Format("<a href='{0}'><span class='glyphicon glyphicon-edit'></span></a>", 
                  @Url.Action("Edit", "Projects", new { Id = model.Id}))).Filterable(false).Sortable(false).Encoded(false);
              columns.Add(model => model.Id).Titled("").RenderedAs(model => String.Format("<a href='{0}'><span class='glyphicon glyphicon-eye-open'></span></a>", 
                  @Url.Action("Details", "Projects", new { Id = model.Id}))).Filterable(false).Sortable(false).Encoded(false);
          })
          .Filterable()
          .Sortable()
          .Empty("Нету данных"))
</div>
